"""Quaranta titoli di articoli, in cinque argomenti. Pochi, per poterli leggere tutti."""

CORPUS = {
    "cucina": [
        "Come si prepara l'arancino siciliano con ragù e piselli",
        "Il supplì romano: riso fritto con mozzarella filante",
        "La cassata siciliana, dolce di ricotta e pasta reale",
        "Pasta alla Norma: melanzane fritte, pomodoro e ricotta salata",
        "Il cannolo siciliano e il segreto della scorza croccante",
        "Granita e brioche, la colazione estiva di Catania",
        "Risotto alla milanese con lo zafferano",
        "Come fare la pizza napoletana a casa con il forno elettrico",
    ],
    "vulcani": [
        "L'Etna è tornato in eruzione: colate laviche sul versante sud",
        "Come si monitora un vulcano attivo con i sismografi",
        "Stromboli, il faro del Mediterraneo che erutta ogni quindici minuti",
        "Il Vesuvio e il rischio per i comuni della zona rossa",
        "Cenere vulcanica: perché l'aeroporto di Catania chiude i voli",
        "Le Eolie, isole nate dal fuoco del sottosuolo",
        "Escursione sui crateri sommitali con una guida alpina",
        "Terremoti e magma: come si legge un'eruzione imminente",
    ],
    "informatica": [
        "Come ottimizzare una query lenta in PostgreSQL con un indice",
        "Django 6.1: le novità del framework per sviluppatori web",
        "Python 3.14 e la versione senza GIL: a che punto siamo",
        "Scrivere test automatici per un'applicazione web",
        "Che cos'è un database relazionale e quando serve",
        "Deploy di un sito su un server Linux con un reverse proxy",
        "Proteggere un'applicazione dagli attacchi di iniezione di codice",
        "Come funziona un token di autenticazione nelle API",
    ],
    "sport": [
        "Il Catania vince il derby con un gol all'ultimo minuto",
        "Maratona di Roma: record di partecipanti e caldo eccezionale",
        "Il tennista italiano conquista il torneo sulla terra rossa",
        "Come allenarsi per la prima mezza maratona in dodici settimane",
        "Il Giro d'Italia attraversa le salite dell'Appennino",
        "Pallavolo: la nazionale femminile batte la Turchia in finale",
        "Nuoto, due record nazionali ai campionati primaverili",
        "La Formula 1 a Monza tra strategie e pioggia improvvisa",
    ],
    "economia": [
        "La borsa di Milano chiude in rialzo trainata dalle banche",
        "Inflazione in calo: che cosa cambia per i mutui a tasso variabile",
        "Come si legge un bilancio aziendale senza essere ragionieri",
        "Il prezzo del petrolio sale e pesa sul costo della benzina",
        "Startup italiane: i finanziamenti crescono nel secondo trimestre",
        "La Banca centrale europea lascia invariati i tassi di interesse",
        "Cosa sono gli ETF e perché li comprano i piccoli risparmiatori",
        "Il turismo in Sicilia traina l'occupazione estiva",
    ],
}
