# Generated by Django 6.1.1 on 2026-10-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campagna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oggetto", models.CharField(max_length=200)),
                (
                    "corpo",
                    models.TextField(
                        help_text="Usa {nome} per il nome del destinatario."
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bozza", "Bozza"),
                            ("in_invio", "In invio"),
                            ("completata", "Completata"),
                        ],
                        default="bozza",
                        max_length=12,
                    ),
                ),
                ("creata", models.DateTimeField(auto_now_add=True)),
                ("avviata_il", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "campagne",
                "ordering": ["-creata", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Contatto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("attivo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Consegna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("in_attesa", "In attesa"),
                            ("inviata", "Inviata"),
                            ("fallita", "Fallita"),
                        ],
                        default="in_attesa",
                        max_length=10,
                    ),
                ),
                ("tentativi", models.PositiveSmallIntegerField(default=0)),
                ("ultimo_errore", models.TextField(blank=True)),
                ("inviata_il", models.DateTimeField(blank=True, null=True)),
                ("dovuta_il", models.DateTimeField(blank=True, null=True)),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consegne",
                        to="campagne.campagna",
                    ),
                ),
                (
                    "contatto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consegne",
                        to="campagne.contatto",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "indexes": [
                    models.Index(
                        fields=["campagna", "stato"], name="consegna_campagna_stato"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campagna", "contatto"),
                        name="una_consegna_per_contatto",
                    )
                ],
            },
        ),
    ]
