# Generated by Django 6.1.1 on 2026-10-01 13:13

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("frasi", "0001_estensione_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo", models.CharField(max_length=300, unique=True)),
                ("argomento", models.CharField(max_length=40)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["argomento", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PuntoProva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gruppo", models.PositiveSmallIntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="puntoprova_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
