# Generated by Django 6.1.1 on 2026-09-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contatto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                (
                    "citta",
                    models.CharField(blank=True, max_length=80, verbose_name="città"),
                ),
                ("creato", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "contatti",
                "ordering": ["nome", "pk"],
            },
        ),
    ]
