# Generated by Django 6.1.1 on 2026-09-30 22:49

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "categorie",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Articolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("sommario", models.CharField(blank=True, max_length=300)),
                ("testo", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                    ),
                ),
                ("copertina", models.ImageField(blank=True, upload_to="copertine/")),
                ("metadati", models.JSONField(blank=True, null=True)),
                ("pubblicato", models.BooleanField(default=False)),
                ("pubblicato_il", models.DateTimeField(blank=True, null=True)),
                ("creato", models.DateTimeField(auto_now_add=True)),
                (
                    "ricerca",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.CombinedSearchVector(
                                django.contrib.postgres.search.SearchVector(
                                    "titolo", config="italian", weight="A"
                                ),
                                "||",
                                django.contrib.postgres.search.SearchVector(
                                    "sommario", config="italian", weight="B"
                                ),
                                django.contrib.postgres.search.SearchConfig("italian"),
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "testo", config="italian", weight="C"
                            ),
                            django.contrib.postgres.search.SearchConfig("italian"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DB_SET_NULL,
                        related_name="articoli",
                        to="articoli.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "articolo",
                "verbose_name_plural": "articoli",
                "ordering": ["-pubblicato_il", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Commento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autore", models.CharField(max_length=80)),
                ("testo", models.TextField()),
                ("creato", models.DateTimeField(auto_now_add=True)),
                (
                    "articolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="commenti",
                        to="articoli.articolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "commento",
                "verbose_name_plural": "commenti",
                "ordering": ["creato", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="articolo",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ricerca"], name="articoli_ar_ricerca_5640e0_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="articolo",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="articoli_ar_tags_42a727_gin"
            ),
        ),
    ]
