# Generated by Django 6.1.1 on 2026-10-01 17:29

import django.db.models.deletion
import django.db.models.functions.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("testo", models.TextField()),
                ("creato", models.DateTimeField(auto_now_add=True)),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documenti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creato", "-id"],
            },
        ),
    ]
