# Generated by Django 6.1.1 on 2026-10-01 15:29

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        VectorExtension(),
    ]
