# Generated by Django 6.1.1 on 2026-10-01 15:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.uuid
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conoscenza", "0001_estensione_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("percorso", models.CharField(max_length=200, unique=True)),
                ("titolo", models.CharField(max_length=200)),
                ("hash", models.CharField(max_length=64)),
                ("importato_il", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["titolo"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("posizione", models.PositiveSmallIntegerField()),
                ("sezione", models.CharField(blank=True, max_length=200)),
                ("testo", models.TextField()),
                (
                    "ricerca",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.SearchVector(
                                "sezione", config="italian", weight="B"
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "testo", config="italian", weight="A"
                            ),
                            django.contrib.postgres.search.SearchConfig("italian"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("modello", models.CharField(blank=True, max_length=100)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="chunk",
                        to="conoscenza.documento",
                    ),
                ),
            ],
            options={
                "ordering": ["documento", "posizione"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["ricerca"], name="chunk_ricerca_gin"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="chunk_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("documento", "posizione"), name="chunk_posizione_unica"
                    )
                ],
            },
        ),
    ]
