# Generated by Django 6.1.1 on 2026-09-30 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60, unique=True)),
            ],
            options={
                "verbose_name_plural": "categorie",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Ordine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("creato", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creato", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descrizione", models.TextField(blank=True)),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=8)),
                ("giacenza", models.PositiveIntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prodotti",
                        to="vetrina.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "prodotti",
                "ordering": ["nome", "pk"],
            },
        ),
        migrations.CreateModel(
            name="RigaOrdine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantita", models.PositiveIntegerField()),
                (
                    "prezzo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "ordine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="righe",
                        to="vetrina.ordine",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vetrina.prodotto",
                    ),
                ),
            ],
        ),
    ]
