# Generated by Django 6.1.1 on 2026-09-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Progetto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "progetti",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Attivita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("descrizione", models.TextField(blank=True)),
                ("completata", models.BooleanField(default=False)),
                ("scadenza", models.DateField(blank=True, null=True)),
                ("creata", models.DateTimeField(auto_now_add=True)),
                (
                    "progetto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attivita",
                        to="todo.progetto",
                    ),
                ),
            ],
            options={
                "verbose_name": "attività",
                "verbose_name_plural": "attività",
                "ordering": ["completata", "-creata", "-pk"],
            },
        ),
    ]
