# Generated by Django 6.1.1 on 2026-10-01 17:29

import django.db.models.deletion
import django.db.models.functions.uuid
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # All'indietro NON si toglie l'estensione: eliminarla cancellerebbe tutte le colonne vettoriali del database.
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name="documento",
            name="stato",
            field=models.CharField(
                choices=[
                    ("bozza", "Bozza"),
                    ("in_revisione", "In revisione"),
                    ("approvato", "Approvato"),
                ],
                default="bozza",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="testo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=40)),
                ("dettaglio", models.CharField(blank=True, max_length=300)),
                ("creato", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventi",
                        to="documenti.documento",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creato", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Versione",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("file", models.FileField(blank=True, upload_to="versioni/%Y/%m/")),
                ("nome_file", models.CharField(max_length=200)),
                ("testo", models.TextField()),
                ("hash", models.CharField(max_length=64)),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("creata", models.DateTimeField(auto_now_add=True)),
                (
                    "autore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versioni",
                        to="documenti.documento",
                    ),
                ),
            ],
            options={
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="Revisione",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modalita",
                    models.CharField(
                        choices=[
                            ("sequenza", "In sequenza"),
                            ("libera", "Libera (decide chi arriva prima)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("messaggio", models.TextField(blank=True)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("aperta", "Aperta"),
                            ("approvata", "Approvata"),
                            ("rimandata", "Rimandata"),
                            ("annullata", "Annullata"),
                        ],
                        default="aperta",
                        max_length=10,
                    ),
                ),
                ("creata", models.DateTimeField(auto_now_add=True)),
                ("conclusa", models.DateTimeField(blank=True, null=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisioni",
                        to="documenti.documento",
                    ),
                ),
                (
                    "versione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documenti.versione",
                    ),
                ),
            ],
            options={
                "ordering": ["-creata", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("posizione", models.PositiveSmallIntegerField()),
                ("testo", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    "versione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk",
                        to="documenti.versione",
                    ),
                ),
            ],
            options={
                "ordering": ["versione", "posizione"],
            },
        ),
        migrations.AddField(
            model_name="documento",
            name="versione_corrente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documenti.versione",
            ),
        ),
        migrations.CreateModel(
            name="Accesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "livello",
                    models.IntegerField(
                        choices=[(1, "Lettura"), (2, "Modifica")], default=1
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessi",
                        to="documenti.documento",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("documento", "utente"), name="un_accesso_per_utente"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Partecipante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveSmallIntegerField()),
                (
                    "decisione",
                    models.CharField(
                        choices=[
                            ("in_attesa", "In attesa"),
                            ("approvato", "Approvato"),
                            ("rimandato", "Rimandato"),
                            ("superato", "Non più necessario"),
                        ],
                        default="in_attesa",
                        max_length=10,
                    ),
                ),
                ("commento", models.TextField(blank=True)),
                ("deciso_il", models.DateTimeField(blank=True, null=True)),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partecipanti",
                        to="documenti.revisione",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("revisione", "utente"), name="un_partecipante_una_volta"
                    ),
                    models.UniqueConstraint(
                        fields=("revisione", "ordine"), name="un_ordine_una_volta"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="versione",
            constraint=models.UniqueConstraint(
                fields=("documento", "numero"), name="una_versione_per_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="revisione",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stato", "aperta")),
                fields=("documento",),
                name="una_revisione_aperta_per_documento",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="chunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("versione", "posizione"), name="chunk_posizione_unica"
            ),
        ),
    ]
