# Generated by Django 6.1.1 on 2026-10-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0003_copia_testo_nelle_versioni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="testo",
        ),
    ]
