# Generated by Django 6.1.1 on 2026-10-01 17:03

import django.db.models.deletion
import django.db.models.functions.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizzazione",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Il sottodominio: acme → acme.localhost", unique=True
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("mailer", models.CharField(default="default", max_length=30)),
                ("creata", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "organizzazioni",
            },
        ),
        migrations.CreateModel(
            name="ViolazioneCsp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("direttiva", models.CharField(max_length=100)),
                ("risorsa_bloccata", models.CharField(blank=True, max_length=500)),
                ("documento", models.CharField(blank=True, max_length=500)),
                ("solo_osservazione", models.BooleanField(default=False)),
                ("ricevuta", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-ricevuta", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruolo",
                    models.IntegerField(
                        choices=[(1, "Lettore"), (2, "Agente"), (3, "Amministratore")],
                        default=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membri",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizzazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membri",
                        to="assistenza.organizzazione",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiaveApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefisso", models.CharField(max_length=12, unique=True)),
                ("impronta", models.CharField(max_length=64)),
                ("creata", models.DateTimeField(auto_now_add=True)),
                ("revocata_il", models.DateTimeField(blank=True, null=True)),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chiavi",
                        to="assistenza.membro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("descrizione", models.TextField(blank=True)),
                ("richiedente", models.EmailField(max_length=254)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("aperto", "Aperto"),
                            ("in_lavorazione", "In lavorazione"),
                            ("chiuso", "Chiuso"),
                        ],
                        default="aperto",
                        max_length=20,
                    ),
                ),
                (
                    "priorita",
                    models.IntegerField(
                        choices=[(1, "Bassa"), (2, "Normale"), (3, "Alta")], default=2
                    ),
                ),
                ("creato", models.DateTimeField(auto_now_add=True)),
                (
                    "assegnato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assistenza.membro",
                    ),
                ),
                (
                    "organizzazione",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assistenza.organizzazione",
                    ),
                ),
            ],
            options={
                "ordering": ["-creato", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Commento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("testo", models.TextField()),
                ("creato", models.DateTimeField(auto_now_add=True)),
                (
                    "autore",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assistenza.membro",
                    ),
                ),
                (
                    "organizzazione",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assistenza.organizzazione",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commenti",
                        to="assistenza.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["creato", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="membro",
            constraint=models.UniqueConstraint(
                fields=("user", "organizzazione"), name="un_ruolo_per_organizzazione"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organizzazione", "stato", "-creato"],
                name="ticket_org_stato_creato",
            ),
        ),
    ]
